# Prefix key
unbind C-b
set-option -g prefix C-Space
bind-key C-Space send-prefix

# misc
set-option -g focus-events on
set -gq allow-passthrough on
set -g visual-activity off
set-option -g terminal-features 'xterm*:clipboard:ccolour:cstyle:focus:title,screen*:title,rxvt*:ignorefkeys,xterm-256color:RGB,tmux-256color:RGB'

# Extended keys
set -g extended-keys-format csi-u
set -g extended-keys on

# Vi mode
set-window-option -g mode-keys vi
bind-key -T copy-mode-vi v send -X begin-selection
bind-key -T copy-mode-vi V send -X select-line
bind-key -T copy-mode-vi y send -X copy-pipe-and-cancel 'pbcopy'

# Status Bar
set -g status on
set -g status-position bottom
set -g status-justify left

# Status left: session name
set -g status-left-length 30

# Status right: date/time
set -g status-right-length 50

# Bit-Mage theme
set -g default-terminal "tmux-256color"
set -g status-style "bg=#000000,fg=#22dd22"
set -g status-left "#[bg=#000000,fg=#00ffff,bold] 󰣇 #S #[bg=#000000,fg=#7b68ee,nobold] "
set -g status-right "#[bg=#000000,fg=#7b68ee] #[bg=#000000,fg=#00ffff] %Y-%m-%d #[bg=#000000,fg=#ffd700] #[bg=#101010,fg=#00ff7f,bold] %H:%M "
set -g window-status-style "bg=#000000,fg=#6f6f6f"
set -g window-status-format "#[fg=#7b68ee]#[fg=#808080] #I:#W "
set -g window-status-current-style "bg=#101010,fg=#00ffff,bold"
set -g window-status-current-format "#[fg=#7b68ee]#[bg=#7b68ee,fg=#000000,bold] #I:#W#{?window_zoomed_flag, ,} #[bg=#000000,fg=#7b68ee,nobold]"
set -g window-status-last-style "bg=#000000,fg=#00ff7f,bold"
set -g window-status-activity-style "bg=#101010,fg=#ffd700,bold"
set -g window-status-bell-style "bg=#ff5f5f,fg=#000000,bold"
set -g pane-border-style "fg=#7b68ee"
set -g pane-active-border-style "fg=#00ffff"
set -g message-style "bg=#101010,fg=#ffd700,bold"
set -g message-command-style "bg=#101010,fg=#00ffff,bold"
set -g mode-style "bg=#7b68ee,fg=#000000,bold"
set -g clock-mode-colour "#00ff7f"
set -g display-panes-colour "#7b68ee"
set -g display-panes-active-colour "#00ffff"
# Vim-style pane navigation
bind -r h select-pane -L
bind -r j select-pane -D
bind -r k select-pane -U
bind -r l select-pane -R

# Plugins
set-environment -g TMUX_PLUGIN_MANAGER_PATH '~/.tmux/plugins'
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-pain-control'
set -g @plugin 'bjesus/muxile'

run '~/.tmux/plugins/tpm/tpm'
